// Generated by hand to mirror `supabase gen types typescript --local`.
// Re-run `pnpm --filter @reverb/db db:types` once a local Supabase stack is
// running; the CLI overwrites this file with its own output.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      households: {
        Row: {
          id: string;
          name: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          household_id: string;
          display_name: string;
          avatar_url: string | null;
          locale: string | null;
          timezone: string;
          reminder_enabled: boolean;
          reminder_time: string;
          onboarded_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          household_id: string;
          display_name: string;
          avatar_url?: string | null;
          locale?: string | null;
          timezone?: string;
          reminder_enabled?: boolean;
          reminder_time?: string;
          onboarded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          display_name?: string;
          avatar_url?: string | null;
          locale?: string | null;
          timezone?: string;
          reminder_enabled?: boolean;
          reminder_time?: string;
          onboarded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
        ];
      };
      lessons: {
        Row: {
          id: string;
          household_id: string;
          title: string;
          description: string | null;
          source_language: string | null;
          target_language: string | null;
          recorded_at: string | null;
          status: Database["public"]["Enums"]["lesson_status"];
          duration_ms: number | null;
          metadata: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          title: string;
          description?: string | null;
          source_language?: string | null;
          target_language?: string | null;
          recorded_at?: string | null;
          status?: Database["public"]["Enums"]["lesson_status"];
          duration_ms?: number | null;
          metadata?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          title?: string;
          description?: string | null;
          source_language?: string | null;
          target_language?: string | null;
          recorded_at?: string | null;
          status?: Database["public"]["Enums"]["lesson_status"];
          duration_ms?: number | null;
          metadata?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "lessons_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
        ];
      };
      lesson_files: {
        Row: {
          id: string;
          lesson_id: string;
          kind: Database["public"]["Enums"]["lesson_file_kind"];
          storage_bucket: string;
          storage_path: string;
          mime_type: string | null;
          byte_size: number | null;
          duration_ms: number | null;
          checksum: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          lesson_id: string;
          kind: Database["public"]["Enums"]["lesson_file_kind"];
          storage_bucket: string;
          storage_path: string;
          mime_type?: string | null;
          byte_size?: number | null;
          duration_ms?: number | null;
          checksum?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          kind?: Database["public"]["Enums"]["lesson_file_kind"];
          storage_bucket?: string;
          storage_path?: string;
          mime_type?: string | null;
          byte_size?: number | null;
          duration_ms?: number | null;
          checksum?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "lesson_files_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      lesson_jobs: {
        Row: {
          id: string;
          lesson_id: string;
          status: Database["public"]["Enums"]["lesson_processing_status"];
          idempotency_key: string;
          attempt_count: number;
          trigger_run_id: string | null;
          provider_metadata: Json;
          payload: Json;
          error_summary: string | null;
          queued_at: string;
          started_at: string | null;
          finished_at: string | null;
          failed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lesson_id: string;
          status?: Database["public"]["Enums"]["lesson_processing_status"];
          idempotency_key: string;
          attempt_count?: number;
          trigger_run_id?: string | null;
          provider_metadata?: Json;
          payload?: Json;
          error_summary?: string | null;
          queued_at?: string;
          started_at?: string | null;
          finished_at?: string | null;
          failed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          status?: Database["public"]["Enums"]["lesson_processing_status"];
          idempotency_key?: string;
          attempt_count?: number;
          trigger_run_id?: string | null;
          provider_metadata?: Json;
          payload?: Json;
          error_summary?: string | null;
          queued_at?: string;
          started_at?: string | null;
          finished_at?: string | null;
          failed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "lesson_jobs_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: true;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      transcript_segments: {
        Row: {
          id: string;
          lesson_id: string;
          segment_index: number;
          start_ms: number;
          end_ms: number;
          speaker: string | null;
          speaker_confidence: number | null;
          speaker_notes: string | null;
          speaker_low_priority: boolean;
          language: string | null;
          text: string;
          translation: string | null;
          translation_language: string | null;
          translated_at: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          lesson_id: string;
          segment_index: number;
          start_ms: number;
          end_ms: number;
          speaker?: string | null;
          speaker_confidence?: number | null;
          speaker_notes?: string | null;
          speaker_low_priority?: boolean;
          language?: string | null;
          text: string;
          translation?: string | null;
          translation_language?: string | null;
          translated_at?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          segment_index?: number;
          start_ms?: number;
          end_ms?: number;
          speaker?: string | null;
          speaker_confidence?: number | null;
          speaker_notes?: string | null;
          speaker_low_priority?: boolean;
          language?: string | null;
          text?: string;
          translation?: string | null;
          translation_language?: string | null;
          translated_at?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "transcript_segments_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      transcript_words: {
        Row: {
          id: string;
          segment_id: string;
          lesson_id: string;
          word_index: number;
          start_ms: number;
          end_ms: number;
          text: string;
          confidence: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          segment_id: string;
          lesson_id: string;
          word_index: number;
          start_ms: number;
          end_ms: number;
          text: string;
          confidence?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          segment_id?: string;
          lesson_id?: string;
          word_index?: number;
          start_ms?: number;
          end_ms?: number;
          text?: string;
          confidence?: number | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "transcript_words_segment_id_fkey";
            columns: ["segment_id"];
            isOneToOne: false;
            referencedRelation: "transcript_segments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "transcript_words_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      extraction_runs: {
        Row: {
          id: string;
          lesson_id: string;
          kind: Database["public"]["Enums"]["extraction_run_kind"];
          status: Database["public"]["Enums"]["extraction_run_status"];
          model: string | null;
          prompt_version: string | null;
          input: Json;
          output: Json;
          error: string | null;
          cost_cents: number | null;
          started_at: string | null;
          finished_at: string | null;
          version: number;
          superseded_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lesson_id: string;
          kind: Database["public"]["Enums"]["extraction_run_kind"];
          status?: Database["public"]["Enums"]["extraction_run_status"];
          model?: string | null;
          prompt_version?: string | null;
          input?: Json;
          output?: Json;
          error?: string | null;
          cost_cents?: number | null;
          started_at?: string | null;
          finished_at?: string | null;
          version?: number;
          superseded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          kind?: Database["public"]["Enums"]["extraction_run_kind"];
          status?: Database["public"]["Enums"]["extraction_run_status"];
          model?: string | null;
          prompt_version?: string | null;
          input?: Json;
          output?: Json;
          error?: string | null;
          cost_cents?: number | null;
          started_at?: string | null;
          finished_at?: string | null;
          version?: number;
          superseded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "extraction_runs_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      extraction_flags: {
        Row: {
          id: string;
          household_id: string;
          lesson_id: string;
          target_kind: Database["public"]["Enums"]["extraction_flag_target_kind"];
          target_id: string;
          reason: Database["public"]["Enums"]["extraction_flag_reason"];
          notes: string | null;
          flagged_by: string;
          extraction_run_id: string | null;
          model: string | null;
          prompt_version: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          lesson_id: string;
          target_kind: Database["public"]["Enums"]["extraction_flag_target_kind"];
          target_id: string;
          reason: Database["public"]["Enums"]["extraction_flag_reason"];
          notes?: string | null;
          flagged_by: string;
          extraction_run_id?: string | null;
          model?: string | null;
          prompt_version?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          lesson_id?: string;
          target_kind?: Database["public"]["Enums"]["extraction_flag_target_kind"];
          target_id?: string;
          reason?: Database["public"]["Enums"]["extraction_flag_reason"];
          notes?: string | null;
          flagged_by?: string;
          extraction_run_id?: string | null;
          model?: string | null;
          prompt_version?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "extraction_flags_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "extraction_flags_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "extraction_flags_extraction_run_id_fkey";
            columns: ["extraction_run_id"];
            isOneToOne: false;
            referencedRelation: "extraction_runs";
            referencedColumns: ["id"];
          },
        ];
      };
      vocab_items: {
        Row: {
          id: string;
          household_id: string;
          lesson_id: string | null;
          lemma: string;
          reading: string | null;
          translation: string | null;
          part_of_speech: string | null;
          example_sentence: string | null;
          example_translation: string | null;
          audio_storage_bucket: string | null;
          audio_storage_path: string | null;
          difficulty: number | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          lesson_id?: string | null;
          lemma: string;
          reading?: string | null;
          translation?: string | null;
          part_of_speech?: string | null;
          example_sentence?: string | null;
          example_translation?: string | null;
          audio_storage_bucket?: string | null;
          audio_storage_path?: string | null;
          difficulty?: number | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          lesson_id?: string | null;
          lemma?: string;
          reading?: string | null;
          translation?: string | null;
          part_of_speech?: string | null;
          example_sentence?: string | null;
          example_translation?: string | null;
          audio_storage_bucket?: string | null;
          audio_storage_path?: string | null;
          difficulty?: number | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "vocab_items_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "vocab_items_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      user_known_words: {
        Row: {
          user_id: string;
          vocab_item_id: string;
          source: string;
          marked_at: string;
        };
        Insert: {
          user_id: string;
          vocab_item_id: string;
          source?: string;
          marked_at?: string;
        };
        Update: {
          user_id?: string;
          vocab_item_id?: string;
          source?: string;
          marked_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_known_words_vocab_item_id_fkey";
            columns: ["vocab_item_id"];
            isOneToOne: false;
            referencedRelation: "vocab_items";
            referencedColumns: ["id"];
          },
        ];
      };
      cards: {
        Row: {
          id: string;
          user_id: string;
          vocab_item_id: string;
          state: Database["public"]["Enums"]["card_state"];
          due_at: string;
          stability: number;
          difficulty: number;
          reps: number;
          lapses: number;
          scheduled_days: number;
          elapsed_days: number;
          last_reviewed_at: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          vocab_item_id: string;
          state?: Database["public"]["Enums"]["card_state"];
          due_at?: string;
          stability?: number;
          difficulty?: number;
          reps?: number;
          lapses?: number;
          scheduled_days?: number;
          elapsed_days?: number;
          last_reviewed_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          vocab_item_id?: string;
          state?: Database["public"]["Enums"]["card_state"];
          due_at?: string;
          stability?: number;
          difficulty?: number;
          reps?: number;
          lapses?: number;
          scheduled_days?: number;
          elapsed_days?: number;
          last_reviewed_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "cards_vocab_item_id_fkey";
            columns: ["vocab_item_id"];
            isOneToOne: false;
            referencedRelation: "vocab_items";
            referencedColumns: ["id"];
          },
        ];
      };
      card_reviews: {
        Row: {
          id: string;
          card_id: string;
          user_id: string;
          rating: Database["public"]["Enums"]["review_rating"];
          elapsed_ms: number | null;
          reviewed_at: string;
          previous_state: Database["public"]["Enums"]["card_state"] | null;
          previous_stability: number | null;
          previous_difficulty: number | null;
          next_state: Database["public"]["Enums"]["card_state"] | null;
          next_stability: number | null;
          next_difficulty: number | null;
          next_due_at: string | null;
          metadata: Json;
        };
        Insert: {
          id?: string;
          card_id: string;
          user_id: string;
          rating: Database["public"]["Enums"]["review_rating"];
          elapsed_ms?: number | null;
          reviewed_at?: string;
          previous_state?: Database["public"]["Enums"]["card_state"] | null;
          previous_stability?: number | null;
          previous_difficulty?: number | null;
          next_state?: Database["public"]["Enums"]["card_state"] | null;
          next_stability?: number | null;
          next_difficulty?: number | null;
          next_due_at?: string | null;
          metadata?: Json;
        };
        Update: {
          id?: string;
          card_id?: string;
          user_id?: string;
          rating?: Database["public"]["Enums"]["review_rating"];
          elapsed_ms?: number | null;
          reviewed_at?: string;
          previous_state?: Database["public"]["Enums"]["card_state"] | null;
          previous_stability?: number | null;
          previous_difficulty?: number | null;
          next_state?: Database["public"]["Enums"]["card_state"] | null;
          next_stability?: number | null;
          next_difficulty?: number | null;
          next_due_at?: string | null;
          metadata?: Json;
        };
        Relationships: [
          {
            foreignKeyName: "card_reviews_card_id_fkey";
            columns: ["card_id"];
            isOneToOne: false;
            referencedRelation: "cards";
            referencedColumns: ["id"];
          },
        ];
      };
      grammar_patterns: {
        Row: {
          id: string;
          household_id: string;
          lesson_id: string | null;
          pattern: string;
          description: string | null;
          examples: Json;
          difficulty: number | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          lesson_id?: string | null;
          pattern: string;
          description?: string | null;
          examples?: Json;
          difficulty?: number | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          lesson_id?: string | null;
          pattern?: string;
          description?: string | null;
          examples?: Json;
          difficulty?: number | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "grammar_patterns_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "grammar_patterns_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      grammar_exercises: {
        Row: {
          id: string;
          household_id: string;
          lesson_id: string | null;
          grammar_pattern_id: string | null;
          kind: Database["public"]["Enums"]["grammar_exercise_kind"];
          prompt: string;
          answer: string;
          choices: Json;
          explanation: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          lesson_id?: string | null;
          grammar_pattern_id?: string | null;
          kind: Database["public"]["Enums"]["grammar_exercise_kind"];
          prompt: string;
          answer: string;
          choices?: Json;
          explanation?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          lesson_id?: string | null;
          grammar_pattern_id?: string | null;
          kind?: Database["public"]["Enums"]["grammar_exercise_kind"];
          prompt?: string;
          answer?: string;
          choices?: Json;
          explanation?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "grammar_exercises_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "grammar_exercises_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "grammar_exercises_grammar_pattern_id_fkey";
            columns: ["grammar_pattern_id"];
            isOneToOne: false;
            referencedRelation: "grammar_patterns";
            referencedColumns: ["id"];
          },
        ];
      };
      dialogue_clips: {
        Row: {
          id: string;
          household_id: string;
          lesson_id: string;
          segment_id: string | null;
          start_ms: number;
          end_ms: number;
          storage_bucket: string;
          storage_path: string;
          caption: string | null;
          translation: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          lesson_id: string;
          segment_id?: string | null;
          start_ms: number;
          end_ms: number;
          storage_bucket: string;
          storage_path: string;
          caption?: string | null;
          translation?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          lesson_id?: string;
          segment_id?: string | null;
          start_ms?: number;
          end_ms?: number;
          storage_bucket?: string;
          storage_path?: string;
          caption?: string | null;
          translation?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "dialogue_clips_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "dialogue_clips_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "dialogue_clips_segment_id_fkey";
            columns: ["segment_id"];
            isOneToOne: false;
            referencedRelation: "transcript_segments";
            referencedColumns: ["id"];
          },
        ];
      };
      teacher_corrections: {
        Row: {
          id: string;
          household_id: string;
          lesson_id: string;
          segment_id: string | null;
          kind: Database["public"]["Enums"]["teacher_correction_kind"];
          source_text: string;
          corrected_text: string;
          explanation: string | null;
          confidence: number | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          lesson_id: string;
          segment_id?: string | null;
          kind: Database["public"]["Enums"]["teacher_correction_kind"];
          source_text: string;
          corrected_text: string;
          explanation?: string | null;
          confidence?: number | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          lesson_id?: string;
          segment_id?: string | null;
          kind?: Database["public"]["Enums"]["teacher_correction_kind"];
          source_text?: string;
          corrected_text?: string;
          explanation?: string | null;
          confidence?: number | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "teacher_corrections_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "teacher_corrections_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "teacher_corrections_segment_id_fkey";
            columns: ["segment_id"];
            isOneToOne: false;
            referencedRelation: "transcript_segments";
            referencedColumns: ["id"];
          },
        ];
      };
      practice_sessions: {
        Row: {
          id: string;
          user_id: string;
          lesson_id: string | null;
          status: Database["public"]["Enums"]["practice_session_status"];
          started_at: string;
          ended_at: string | null;
          duration_ms: number | null;
          xp_earned: number;
          cards_reviewed: number;
          exercises_attempted: number;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          lesson_id?: string | null;
          status?: Database["public"]["Enums"]["practice_session_status"];
          started_at?: string;
          ended_at?: string | null;
          duration_ms?: number | null;
          xp_earned?: number;
          cards_reviewed?: number;
          exercises_attempted?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          lesson_id?: string | null;
          status?: Database["public"]["Enums"]["practice_session_status"];
          started_at?: string;
          ended_at?: string | null;
          duration_ms?: number | null;
          xp_earned?: number;
          cards_reviewed?: number;
          exercises_attempted?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "practice_sessions_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      practice_session_items: {
        Row: {
          id: string;
          session_id: string;
          user_id: string;
          position: number;
          kind: Database["public"]["Enums"]["practice_item_kind"];
          card_id: string | null;
          grammar_exercise_id: string | null;
          dialogue_clip_id: string | null;
          shown_at: string | null;
          answered_at: string | null;
          rating: Database["public"]["Enums"]["review_rating"] | null;
          correct: boolean | null;
          response_ms: number | null;
          metadata: Json;
        };
        Insert: {
          id?: string;
          session_id: string;
          user_id: string;
          position: number;
          kind: Database["public"]["Enums"]["practice_item_kind"];
          card_id?: string | null;
          grammar_exercise_id?: string | null;
          dialogue_clip_id?: string | null;
          shown_at?: string | null;
          answered_at?: string | null;
          rating?: Database["public"]["Enums"]["review_rating"] | null;
          correct?: boolean | null;
          response_ms?: number | null;
          metadata?: Json;
        };
        Update: {
          id?: string;
          session_id?: string;
          user_id?: string;
          position?: number;
          kind?: Database["public"]["Enums"]["practice_item_kind"];
          card_id?: string | null;
          grammar_exercise_id?: string | null;
          dialogue_clip_id?: string | null;
          shown_at?: string | null;
          answered_at?: string | null;
          rating?: Database["public"]["Enums"]["review_rating"] | null;
          correct?: boolean | null;
          response_ms?: number | null;
          metadata?: Json;
        };
        Relationships: [
          {
            foreignKeyName: "practice_session_items_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "practice_sessions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "practice_session_items_card_id_fkey";
            columns: ["card_id"];
            isOneToOne: false;
            referencedRelation: "cards";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "practice_session_items_grammar_exercise_id_fkey";
            columns: ["grammar_exercise_id"];
            isOneToOne: false;
            referencedRelation: "grammar_exercises";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "practice_session_items_dialogue_clip_id_fkey";
            columns: ["dialogue_clip_id"];
            isOneToOne: false;
            referencedRelation: "dialogue_clips";
            referencedColumns: ["id"];
          },
        ];
      };
      practice_events: {
        Row: {
          id: string;
          user_id: string;
          session_id: string | null;
          session_item_id: string | null;
          kind: Database["public"]["Enums"]["practice_event_kind"];
          occurred_at: string;
          payload: Json;
        };
        Insert: {
          id?: string;
          user_id: string;
          session_id?: string | null;
          session_item_id?: string | null;
          kind: Database["public"]["Enums"]["practice_event_kind"];
          occurred_at?: string;
          payload?: Json;
        };
        Update: {
          id?: string;
          user_id?: string;
          session_id?: string | null;
          session_item_id?: string | null;
          kind?: Database["public"]["Enums"]["practice_event_kind"];
          occurred_at?: string;
          payload?: Json;
        };
        Relationships: [
          {
            foreignKeyName: "practice_events_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "practice_sessions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "practice_events_session_item_id_fkey";
            columns: ["session_item_id"];
            isOneToOne: false;
            referencedRelation: "practice_session_items";
            referencedColumns: ["id"];
          },
        ];
      };
      streaks: {
        Row: {
          user_id: string;
          current_length: number;
          longest_length: number;
          last_practiced_on: string | null;
          timezone: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          current_length?: number;
          longest_length?: number;
          last_practiced_on?: string | null;
          timezone?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          current_length?: number;
          longest_length?: number;
          last_practiced_on?: string | null;
          timezone?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notification_events: {
        Row: {
          id: string;
          user_id: string;
          lesson_id: string | null;
          kind: Database["public"]["Enums"]["notification_event_kind"];
          channel: Database["public"]["Enums"]["notification_channel"];
          status: Database["public"]["Enums"]["notification_status"];
          scheduled_for: string | null;
          sent_at: string | null;
          read_at: string | null;
          payload: Json;
          error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          lesson_id?: string | null;
          kind: Database["public"]["Enums"]["notification_event_kind"];
          channel: Database["public"]["Enums"]["notification_channel"];
          status?: Database["public"]["Enums"]["notification_status"];
          scheduled_for?: string | null;
          sent_at?: string | null;
          read_at?: string | null;
          payload?: Json;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          lesson_id?: string | null;
          kind?: Database["public"]["Enums"]["notification_event_kind"];
          channel?: Database["public"]["Enums"]["notification_channel"];
          status?: Database["public"]["Enums"]["notification_status"];
          scheduled_for?: string | null;
          sent_at?: string | null;
          read_at?: string | null;
          payload?: Json;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notification_events_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      correction_drills: {
        Row: {
          id: string;
          user_id: string;
          teacher_correction_id: string;
          state: Database["public"]["Enums"]["correction_drill_state"];
          due_at: string;
          attempts: number;
          passes: number;
          fails: number;
          consecutive_passes: number;
          last_result: Database["public"]["Enums"]["correction_drill_result"] | null;
          last_attempted_at: string | null;
          retired_at: string | null;
          xp_earned: number;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          teacher_correction_id: string;
          state?: Database["public"]["Enums"]["correction_drill_state"];
          due_at?: string;
          attempts?: number;
          passes?: number;
          fails?: number;
          consecutive_passes?: number;
          last_result?: Database["public"]["Enums"]["correction_drill_result"] | null;
          last_attempted_at?: string | null;
          retired_at?: string | null;
          xp_earned?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          teacher_correction_id?: string;
          state?: Database["public"]["Enums"]["correction_drill_state"];
          due_at?: string;
          attempts?: number;
          passes?: number;
          fails?: number;
          consecutive_passes?: number;
          last_result?: Database["public"]["Enums"]["correction_drill_result"] | null;
          last_attempted_at?: string | null;
          retired_at?: string | null;
          xp_earned?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "correction_drills_teacher_correction_id_fkey";
            columns: ["teacher_correction_id"];
            isOneToOne: false;
            referencedRelation: "teacher_corrections";
            referencedColumns: ["id"];
          },
        ];
      };
      correction_drill_attempts: {
        Row: {
          id: string;
          drill_id: string;
          user_id: string;
          result: Database["public"]["Enums"]["correction_drill_result"];
          response_ms: number | null;
          xp_awarded: number;
          user_response: string | null;
          attempted_at: string;
          metadata: Json;
        };
        Insert: {
          id?: string;
          drill_id: string;
          user_id: string;
          result: Database["public"]["Enums"]["correction_drill_result"];
          response_ms?: number | null;
          xp_awarded?: number;
          user_response?: string | null;
          attempted_at?: string;
          metadata?: Json;
        };
        Update: {
          id?: string;
          drill_id?: string;
          user_id?: string;
          result?: Database["public"]["Enums"]["correction_drill_result"];
          response_ms?: number | null;
          xp_awarded?: number;
          user_response?: string | null;
          attempted_at?: string;
          metadata?: Json;
        };
        Relationships: [
          {
            foreignKeyName: "correction_drill_attempts_drill_id_fkey";
            columns: ["drill_id"];
            isOneToOne: false;
            referencedRelation: "correction_drills";
            referencedColumns: ["id"];
          },
        ];
      };
      tts_assets: {
        Row: {
          id: string;
          household_id: string;
          text_hash: string;
          text: string;
          language_code: string;
          voice_name: string;
          provider: string;
          storage_bucket: string;
          storage_path: string;
          byte_size: number | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          text_hash: string;
          text: string;
          language_code: string;
          voice_name: string;
          provider: string;
          storage_bucket: string;
          storage_path: string;
          byte_size?: number | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          text_hash?: string;
          text?: string;
          language_code?: string;
          voice_name?: string;
          provider?: string;
          storage_bucket?: string;
          storage_path?: string;
          byte_size?: number | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tts_assets_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
        ];
      };
      chat_sessions: {
        Row: {
          id: string;
          user_id: string;
          level: string;
          status: string;
          summary: string | null;
          total_messages: number;
          total_user_messages: number;
          last_message_at: string | null;
          ended_at: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          level?: string;
          status?: string;
          summary?: string | null;
          total_messages?: number;
          total_user_messages?: number;
          last_message_at?: string | null;
          ended_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          level?: string;
          status?: string;
          summary?: string | null;
          total_messages?: number;
          total_user_messages?: number;
          last_message_at?: string | null;
          ended_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      chat_messages: {
        Row: {
          id: string;
          session_id: string;
          user_id: string;
          role: Database["public"]["Enums"]["chat_message_role"];
          content: string;
          language: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          user_id: string;
          role: Database["public"]["Enums"]["chat_message_role"];
          content: string;
          language?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          user_id?: string;
          role?: Database["public"]["Enums"]["chat_message_role"];
          content?: string;
          language?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "chat_messages_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "chat_sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      chat_corrections: {
        Row: {
          id: string;
          message_id: string;
          session_id: string;
          user_id: string;
          kind: Database["public"]["Enums"]["chat_correction_kind"];
          source_text: string;
          corrected_text: string;
          explanation: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          message_id: string;
          session_id: string;
          user_id: string;
          kind?: Database["public"]["Enums"]["chat_correction_kind"];
          source_text: string;
          corrected_text: string;
          explanation?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          message_id?: string;
          session_id?: string;
          user_id?: string;
          kind?: Database["public"]["Enums"]["chat_correction_kind"];
          source_text?: string;
          corrected_text?: string;
          explanation?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "chat_corrections_message_id_fkey";
            columns: ["message_id"];
            isOneToOne: false;
            referencedRelation: "chat_messages";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "chat_corrections_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "chat_sessions";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      current_household_id: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      bump_chat_session_counters: {
        Args: {
          p_session_id: string;
          p_message_increment?: number;
          p_user_message_increment?: number;
        };
        Returns: undefined;
      };
    };
    Enums: {
      lesson_status: "draft" | "uploading" | "processing" | "ready" | "failed" | "archived";
      lesson_file_kind:
        | "audio_source"
        | "audio_clean"
        | "transcript_raw"
        | "transcript_clean"
        | "thumbnail";
      lesson_processing_status:
        | "queued"
        | "transcribing"
        | "diarizing"
        | "extracting"
        | "generating_audio"
        | "ready"
        | "failed";
      extraction_run_kind: "vocab" | "grammar" | "dialogue" | "corrections";
      extraction_run_status: "queued" | "running" | "succeeded" | "failed";
      extraction_flag_target_kind: "vocab" | "grammar" | "dialogue" | "correction";
      extraction_flag_reason:
        | "wrong_translation"
        | "not_a_word"
        | "wrong_split"
        | "duplicate"
        | "low_value"
        | "other";
      card_state: "new" | "learning" | "review" | "relearning";
      review_rating: "again" | "hard" | "good" | "easy";
      grammar_exercise_kind: "fill_blank" | "multiple_choice" | "translate" | "reorder";
      teacher_correction_kind: "grammar" | "vocabulary" | "pronunciation" | "usage";
      practice_session_status: "active" | "completed" | "abandoned";
      practice_item_kind: "card" | "grammar_exercise" | "dialogue_clip";
      practice_event_kind:
        | "session_start"
        | "session_complete"
        | "session_abandon"
        | "item_shown"
        | "item_answered"
        | "item_skipped"
        | "pause"
        | "resume";
      notification_event_kind:
        | "streak_reminder"
        | "session_due"
        | "lesson_ready"
        | "lesson_failed"
        | "milestone";
      notification_channel: "push" | "email" | "in_app";
      notification_status: "queued" | "sent" | "failed" | "cancelled";
      correction_drill_state: "new" | "learning" | "retired";
      correction_drill_result: "pass" | "fail";
      chat_message_role: "user" | "assistant";
      chat_correction_kind: "grammar" | "vocabulary" | "pronunciation" | "usage";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
